markdown: redcarpet
pygments: true
plugins: ./_plugins
paginate: 8
permalink: /:year/:month/:day/:title/

safe: false

#站点基础配置
title: Pretend To Write Like A Hacker
subTitle: besteric.
description: 记录生活点滴，积累沉淀...
url: http://besteric.github.com
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /
  - text: 游戏
    url: ../game/
  - text: 运动
    url: ../sports/
  - text: 路由器
    url: /archives/
  - text: 关于我
    url: ../about/
  - text: 网站日志
    url: ../logs/
  - text: 订阅
    url: /atom.xml

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: http://gtms02.alicdn.com/tps/i2/T1PObnFqBdXXcryKEg-1280-200.jpg
  - item: http://gtms03.alicdn.com/tps/i3/T1U_YlFAlcXXbErygJ-2048-260.jpg
  - item: http://gtms04.alicdn.com/tps/i4/T1K0LLFvVbXXbErygJ-2048-260.jpg
  - item: http://gtms01.alicdn.com/tps/i1/T12DHKFx4bXXbErygJ-2048-260.jpg

#关注我
follow:

  - class: fa-github
    url: http://github.com/besteric
  - class: fa-twitter
    url: http://www.twitter.com/besteric
  - class: fa-rss
    url: http://www.besteric.com/atom.xml

#作者信息
author:
  name: besteric
  link: http://www.besteric.com/contact.html
  img: 

#评论信息
disqus:
  config: false
  id: piznblog

duoshuo:
  config: true
  id: besteric